- // MIR for `mutable` before GVN
+ // MIR for `mutable` after GVN
  
  fn mutable(_1: Wrap<'_>) -> () {
      debug x => _1;
      let mut _0: ();
      let _2: Wrap<'_>;
      let _3: ();
      let mut _4: Wrap<'_>;
      scope 1 {
          debug y => _2;
      }
  
      bb0: {
          StorageLive(_2);
-         _2 = Wrap<'{erased}>(reborrow _1);
+         _2 = copy _1;
          StorageLive(_3);
          StorageLive(_4);
-         _4 = Wrap<'{erased}>(reborrow _2);
+         _4 = copy _2;
          _3 = opaque(move _4) -> [return: bb1, unwind unreachable];
      }
  
      bb1: {
          StorageDead(_4);
          StorageDead(_3);
          _0 = const ();
          StorageDead(_2);
          return;
      }
  }
  
